# Generated by Django 6.0.4 on 2026-05-02 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('sun_needs', models.CharField(default='Full sun', max_length=20)),
                ('water_frequency_days', models.IntegerField(default=2)),
                ('days_to_harvest', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('planted_date', models.DateField()),
                ('last_watered', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.garden')),
                ('plant_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.plantinfo')),
            ],
        ),
    ]
